name: mobileauthdemo

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  fhir: ^0.4.6
  fhir_auth:
    path: ../../fhir_auth
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true