name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  fhir_yaml:
    git:
      url: https://github.com/i-atros/fhir.git
      path: fhir_yaml
      ref: fix-dependencies
  freezed_annotation: 2.2.0
  json_annotation: 4.8.0
  yaml: ^3.1.0

dev_dependencies:
  json_serializable: ^6.5.3
  build_runner: ^2.1.0
  freezed: ^2.2.0
  test: ^1.21.0
