name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.4.8-1
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  fhir_yaml: ^0.4.2
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0
  yaml: ^3.1.0

dev_dependencies:
  json_serializable: ^5.0.0
  build_runner: ^2.0.6
  freezed: ^0.14.3
  test: ^1.17.10
