name: fhir
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=3.0.0 <3.6.0'

dependencies:
  fhir_yaml:
    git:
      url: https://github.com/i-atros/fhir.git
      path: fhir_yaml
      ref: upgrade-dart-sdk
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: 2.4.8
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  test: ^1.21.0
