name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.5.0-2
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  fhir:
    git:
      url: https://github.com/i-atros/fhir.git
      path: fhir
  freezed_annotation: 2.2.0
  http: ^0.13.5

dev_dependencies:
  analyzer: ^4.7.0
  build_runner: ^2.1.0
  freezed: ^2.2.0
  pedantic: ^1.11.1
  test: 1.21.0