name: fhir_yaml
description: Dart package to format JSON data to YAML. Supports formatting conventions of pubspec files.
version: 0.5.0
homepage: https://github.com/MayJuun/fhir/tree/main/fhir_yaml

environment:
  sdk: '>=3.4.4 <4.0.0'

dev_dependencies:
  test: ^1.21.10
  yaml: ^3.1.0
