name: fhir_yaml
description: Dart package to format JSON data to YAML. Supports formatting conventions of pubspec files.
version: 0.4.2
homepage: https://github.com/MayJuun/fhir/tree/main/fhir_yaml

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
  yaml: ^3.1.0
