name: fhir_example
description: Example for fhir library
version: 0.3.0-nullsafety.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  fhir:
    path: ..